In [1]:
import sys, os
sys.path.append(os.pardir)  # 为了导入父目录中的文件而进行的设定
import numpy as np
from common.functions import *
from common.gradient import numerical_gradient

In [24]:
del TwoLayerNet

In [25]:
def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 还原值
        it.iternext()   
        
    return grad

class TwoLayerNet:

    def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):
        # 初始化权重
        self.params = {}
        self.params['W1'] = weight_init_std * np.random.randn(input_size, hidden_size)
        self.params['b1'] = np.zeros(hidden_size)
        self.params['W2'] = weight_init_std * np.random.randn(hidden_size, output_size)
        self.params['b2'] = np.zeros(output_size)

    def predict(self, x):
        W1, W2 = self.params['W1'], self.params['W2']
        b1, b2 = self.params['b1'], self.params['b2']
    
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        y = softmax(a2)
        
        return y
        
    # x:输入数据, t:监督数据
    def loss(self, x, t):
        y = self.predict(x)
        return cross_entropy_error(y, t)
    
    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        t = np.argmax(t, axis=1)
        
        accuracy = np.sum(y == t) / float(x.shape[0])
        return accuracy
        
    # x:输入数据, t:监督数据
    def numerical_gradient(self, x, t):
        loss_W = lambda W: self.loss(x, t)
        grads = {}
        grads['W1'] = numerical_gradient(loss_W, self.params['W1'])
        grads['b1'] = numerical_gradient(loss_W, self.params['b1'])
        grads['W2'] = numerical_gradient(loss_W, self.params['W2'])
        grads['b2'] = numerical_gradient(loss_W, self.params['b2'])
        
        return grads
        
    def gradient(self, x, t):
        W1, W2 = self.params['W1'], self.params['W2']
        b1, b2 = self.params['b1'], self.params['b2']
        grads = {}
        
        batch_num = x.shape[0]
        
        # forward
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        y = softmax(a2)
        
        # backward
        dy = (y - t) / batch_num
        grads['W2'] = np.dot(z1.T, dy)
        grads['b2'] = np.sum(dy, axis=0)
        
        da1 = np.dot(dy, W2.T)
        dz1 = sigmoid_grad(a1) * da1
        grads['W1'] = np.dot(x.T, dz1)
        grads['b1'] = np.sum(dz1, axis=0)

        return grads

In [26]:
net=TwoLayerNet(input_size=2,hidden_size=2,output_size=2)

In [27]:
net.params['b1'].shape

(2,)

In [28]:
x=np.random.rand(100,2)
t=np.random.rand(100,2)

In [29]:
grads=net.numerical_gradient(x[0],t[0])

[[-0.00761139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00781139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00454226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00474226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01045642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01025642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01089192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01109192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771139 -0.00464226]
 [ 0.01035642 -0.01099192]]
[[-0.00771

In [ ]:
grads['W2']

In [ ]:
import matplotlib.pyplot as plt
from dataset.mnist import load_mnist


In [ ]:
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

In [ ]:
network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

In [ ]:
iters_num = 10000  # 适当设定循环的次数
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.1

In [ ]:
train_loss_list = []
train_acc_list = []
test_acc_list = []

In [ ]:
for i in range(iters_num):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]
    
    #grad = network.numerical_gradient(x_batch, t_batch)
    grad = network.gradient(x_batch, t_batch)
    
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]
        
    loss = network.loss(x_batch,t_batch)
    train_loss_list.append(loss)
    print(i)

In [ ]:
xlist=np.arange(len(train_loss_list))
plt.plot(xlist,train_loss_list)

In [ ]:
x=np.array([[1,2,3],[1,2,3]])
it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

In [ ]:
it.finished

In [55]:
del numerical_gradient

In [51]:
def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        print(test)
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 还原值
        it.iternext()
    x=x+1;
    print(test)
    return grad

In [74]:
test=np.array([1.0,2.0,3.0,4.0,5.0])

In [35]:
def function_1(x):
    return np.sum(x**2)

In [72]:
del f

In [73]:
def f(x):
    it = np.nditer(x, flags=['multi_index'])
    while not it.finished:
        idx = it.multi_index;
        x[idx]+=1
        x[idx]-=1
        it.iternext()

In [75]:
print(test)
f(test)
print(test)

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [71]:
test

array([3., 4., 5., 6., 7.])