In [1]:
def mean_squared_error(y,t):
    return 0.5 * np.sum((y-t)**2)

def cross_entropy_error(y,t):
    delta = 1e-7;
    return -np.sum(t*np.log(self.W.shape+delta))

In [ ]:
import sys, os
sys.path.append(os.pardir)  # 为了导入父目录的文件而进行的设定
import numpy as np
import pickle
from dataset.mnist import load_mnist

In [ ]:
(x_train,t_train),(x_test,t_test) = load_mnist(normalize=True,flatten=True, one_hot_label=False)

In [ ]:
#随机抽取数据来进行 mini-batch 学习

In [ ]:
train_size=x_train.shape[0]
batch_size=10

batch_mask=np.random.choice(train_size,batch_size)
x_batch=x_train[batch_mask]
t_batch=t_train[batch_mask]

In [ ]:
batch_mask.size

In [2]:
def cross_entropy_error(y,t):
    if y.ndim==1:
        t=t.reshape(1,t.size);
        y=t.reshape(1,y.size);
    batch_size= y.shape[0];
    return -np.sum(t* np.log(y+1e-7))/batch_size

In [3]:
def numerical_diff(f,x):
    h=0.0001
    return (f(x+h)-f(x-h))/(2*h)

In [ ]:
def function_1(x):
    return 0.01*x**2+0.1*x

In [5]:
import matplotlib.pylab as plt
import numpy as np

In [ ]:
numerical_diff(function_1,5)

In [ ]:
x=np.arange(0,20,0.1)
y=function_1(x)
z=numerical_diff(function_1,5)*(x-5)+function_1(5)
plt.plot(x,y)
plt.plot(x,z)

In [ ]:
def tangent_line(f, x):
    d = numerical_diff(f, x)
    print(d)
    y = f(x) - d*x
    return lambda t: d*t + y #返回一个输入参数是t的函数

In [ ]:
tf = tangent_line(function_1, 5)
y2 = tf(x)

In [ ]:
plt.plot(x, y)
plt.plot(x, y2)
plt.show()

In [37]:
np.array([[2,3],[1,2]]).flatten()

array([2, 3, 1, 2])

In [39]:
def numerical_gradient(f,x):
    h=0.0001;
    
    grad = np.zeros_like(x);
    
    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h;
        fxh1 = f(x);
        x[idx] = tmp_val - h;
        fxh2 = f(x);
        
        grad[idx] = (fxh1-fxh2)/(2*h)
        x[idx] = tmp_val;
        
    return grad

In [63]:
del numerical_gradient

In [53]:
def numerical_gradient(f,x):
    h=0.0001;
    ximd=x.flatten()
    grad = np.zeros_like(ximd);
    
    for idx in range(ximd.size):
        tmp_val = ximd[idx]
        ximd[idx] = float(tmp_val) + h;
        fxh1 = f(ximd.reshape(x.shape));
        ximd[idx] = tmp_val - h;
        fxh2 = f(ximd.reshape(x.shape));
        
        grad[idx] = (fxh1-fxh2)/(2*h)
        ximd[idx] = tmp_val;
        
    return grad.reshape(x.shape)
        

In [65]:
def _numerical_gradient_1d(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 还原值
        
    return grad


def numerical_gradient_2d(f, X):
    if X.ndim == 1:
        return _numerical_gradient_1d(f, X)
    else:
        grad = np.zeros_like(X)
        
        for idx, x in enumerate(X):
            grad[idx] = _numerical_gradient_1d(f, x)
        
        return grad
    
def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x) # f(x+h)
        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        
        x[idx] = tmp_val # 还原值
        it.iternext()   
        
    return grad

In [40]:
def function_2(x):
    return np.sum(x**2)

In [47]:
def function_3(x):
    x1=np.array([0.6,0.9]);
    return np.sum(np.dot(x1,x).flatten())

In [48]:
function_3(np.array([[2,3,4],[4,5,6]]))

18.9

In [66]:
numerical_gradient(function_3,np.array([[2.0,3.0,4.0],[4.0,5.0,6.0]]))
numerical_gradient(function_3,np.array([[2.0,3.0,4.0],[4.0,5.0,6.0]]))

array([[0.6, 0.6, 0.6],
       [0.9, 0.9, 0.9]])

In [41]:
numerical_gradient(function_2,np.array([3.0,4.0]))

array([6., 8.])

In [ ]:
_numerical_gradient_no_batch(function_2,np.array([3.0,4.0]))

In [ ]:
def gradiet_desent(f,init_x,lr=0.01,stp_num=100):
    x=init_x;
    
    for i in range(stp_num):
        grad=numerical_gradient(f,x);
        x=x-lr*grad;
        
    return x
        

In [ ]:
gradiet_desent(function_2,np.array([-3.0,4.0]),lr=0.1,stp_num=100)

In [11]:
def softmax(a):
    c=np.max(a);
    return np.exp(a-c)/(np.sum(np.exp(a-c)))

In [67]:
class simpleNet:
    def __init__(self):
        self.W=np.random.randn(2,3)
        
    def predict(self,x):
        return np.dot(x,self.W)
    
    def loss(self,x,t):
        z = self.predict(x);
        y=softmax(z);
        return cross_entropy_error(y,t)

In [13]:
net=simpleNet()

In [16]:
x=np.array([0.6,0.9])
p=net.predict(x,)

In [19]:
t=np.array([0,0,1])

In [68]:
net.loss(x,t)

16.11809565095832

In [69]:
def f(w):
    return net.loss(x,t)

In [70]:
numerical_gradient(f,net.W)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
list(enumerate(x))

[(0, 0.6), (1, 0.9)]